name: Send Failure Email

on:
  workflow_run:
    workflows: ["Python CI with Logging"]
    types:
      - completed

jobs:
  notify-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_HARSH }}  # This should reference your stored email
          password: ${{ secrets.EMAIL_PASSWORD }}  # This should reference your stored App Password
          subject: "Python CI Failed"
          to: harshvardhanshekhawat815@gmail.com  # The email to receive the failure notification
          from: harshvardhanshekhawat815@gmail.com  # Your email address as the sender
          body: |
            The Python CI workflow failed.
            View logs at: ${{ github.event.workflow_run.html_url }}
